version: "3"

services:
  renderer:
    image: puppeteer:latest
    ports:
      - 8080:3000
    expose:
      - "3000"
    user: root
    working_dir: /app

    # Examples: uncomment a single command at a time.
    #################################################################
    #
    # screenshot
    command: bash -c "npm install --quiet && node examples/screenshot.js"
    #
    # screenshot-fullpage
    #command: bash -c "npm install --quiet && node examples/screenshot-fullpage.js"
    #
    #################################################################


    volumes:
      - ./:/app
