version: "3"

services:
  renderer:
    image: docker-puppeteer:latest
    ports:
      - 8080:3000
    expose:
      - "3000"
    working_dir: /app/puppeteer-renderer
    command: bash -c "npm install --quiet && npm run start"
    volumes:
      - ./:/app
volumes:
 puppeteer-renderer-data-volume:
